In [1]:
import pandas as pd

pd.toNumeric( regex=True) => permet de convertir le type des datas en se basant sur des regex: voir en detail

slugify => remplace une string en string pour url (trim, espace => -, accent => retire, ...), à utiliser pour les clés pour les jointures

str.pad => formate une colonne. ex: les nombres sur 2 chiffres : 01, 02, ...

Supprimer les valeurs aberrantes (après lecture du graphe)

données : open damir


dataframe avec index temporelle: série temporelle => boite a outil de fonctions disponibles (ex: moyenn glissante...)

In [185]:
df_medecin = pd.read_excel('/Users/fabienfluro/Documents/MS_BGD/INFMDI721_Kit_DataScience/Repo_Git/Fabien_Fluro/sante/rpps-medecins18-tab2v5_71029108888648.xlsx', sheet_name='clean', index_col = [0], header=[0], skipinitialspace=True)

df_medecin["REGION"] = df_medecin.index.get_level_values('ZONE INSCRIPT')

df_medecin = df_medecin.reset_index()

df_medecin = df_medecin.drop(['ZONE INSCRIPT', 'Moins de 30 ans', 'Entre 30 et 34 ans', 'Entre 35 et 39 ans', 'Entre 40 et 44 ans', 'Entre 45 et 49 ans', 'Entre 50 et 54 ans', 'Entre 55 et 59 ans', 'Entre 55 et 59 ans', 'Entre 60 et 64 ans', 'Entre 65 et 69 ans', '70 ans et plus'], axis=1)

# Change columns name
df_medecin.columns = ['SPECIALITE', 'NUMBER', 'REGION']

In [186]:
#check regions , we keep only department
df_medecin['REGION'].unique()

array(['FRANCE ENTIERE', 'FRANCE MÈtropolitaine', 'DROM',
       'Auvergne-RhÙne-Alpes', 'Bourgogne-Franche-ComtÈ', 'Bretagne',
       'Centre-Val de Loire', 'Corse', 'Grand Est', 'Guadeloupe',
       'Guyane', 'Hauts-de-France', 'Ile-de-France', 'La RÈunion',
       'Martinique', 'Mayotte', 'Normandie', 'Nouvelle-Aquitaine',
       'Occitanie', 'Pays de la Loire', 'Provence-Alpes-CÙte díAzur',
       '01 - Ain', '02 - Aisne', '03 - Allier',
       '04 - Alpes-de-Haute-Provence', '05 - Hautes-Alpes',
       '06 - Alpes-Maritimes', '07 - ArdËche', '08 - Ardennes',
       '09 - AriËge', '10 - Aube', '11 - Aude', '12 - Aveyron',
       '13 - Bouches-du-RhÙne', '14 - Calvados', '15 - Cantal',
       '16 - Charente', '17 - Charente-Maritime', '18 - Cher',
       '19 - CorrËze', '2A - Corse-du-Sud', '2B - Haute-Corse',
       '21 - CÙte-díOr', '22 - CÙtes-díArmor', '23 - Creuse',
       '24 - Dordogne', '25 - Doubs', '26 - DrÙme', '27 - Eure',
       '28 - Eure-et-Loir', '29 - FinistËre', '30 - Gard',
       '31 - Haute-Garonne', '32 - Gers', '33 - Gironde', '34 - HÈrault',
       '35 - Ille-et-Vilaine', '36 - Indre', '37 - Indre-et-Loire',
       '38 - IsËre', '39 - Jura', '40 - Landes', '41 - Loir-et-Cher',
       '42 - Loire', '43 - Haute-Loire', '44 - Loire-Atlantique',
       '45 - Loiret', '46 - Lot', '47 - Lot-et-Garonne', '48 - LozËre',
       '49 - Maine-et-Loire', '50 - Manche', '51 - Marne',
       '52 - Haute-Marne', '53 - Mayenne', '54 - Meurthe-et-Moselle',
       '55 - Meuse', '56 - Morbihan', '57 - Moselle', '58 - NiËvre',
       '59 - Nord', '60 - Oise', '61 - Orne', '62 - Nord-Pas-de-Calais',
       '63 - Puy-de-DÙme', '64 - PyrÈnÈes-Atlantiques',
       '65 - Hautes-PyrÈnÈes', '66 - PyrÈnÈes-Orientales',
       '67 - Bas-Rhin', '68 - Haut-Rhin', '69 - RhÙne',
       '70 - Haute-SaÙne', '71 - SaÙne-et-Loire', '72 - Sarthe',
       '73 - Savoie', '74 - Haute-Savoie', '75 - Paris',
       '76 - Seine-Maritime', '77 - Seine-et-Marne', '78 - Yvelines',
       '79 - Deux-SËvres', '80 - Somme', '81 - Tarn',
       '82 - Tarn-et-Garonne', '83 - Var', '84 - Vaucluse', '85 - VendÈe',
       '86 - Vienne', '87 - Haute-Vienne', '88 - Vosges', '89 - Yonne',
       '90 - Territoire de Belfort', '91 - Essonne',
       '92 - Hauts-de-Seine', '93 - Seine-Saint-Denis',
       '94 - Val-de-Marne', '95 - Val-díOise', '971 - Guadeloupe',
       '972 - Martinique', '973 - Guyane', '974 - La RÈunion',
       '976 - Mayotte'], dtype=object)

In [187]:
# Garder les regions qui comporte un numero de département
df_medecin = df_medecin[df_medecin['REGION'].str.contains(r'^[0-9]{2,3}.*')]

#reg = r'([\D]*)(?P<Dosage>\d+)(.*),(?P<Galenique>.*)'

# Split numero et nom du département
reg = r'(?P<NUM_DEP>[0-9]{2,3}) - (?P<NOM_DEP>.*)'
df_medecin = pd.concat([df_medecin, df_medecin['REGION'].str.extract(reg, expand=True)], axis=1)


# re order
df_medecin = df_medecin[['NUM_DEP', 'NOM_DEP', 'SPECIALITE', 'NUMBER']]

In [188]:
df_medecin = df_medecin[df_medecin['SPECIALITE'] == 'SpÈcialistes']
df_medecin.head(5)

     NUM_DEP                  NOM_DEP    SPECIALITE  NUMBER
925       01                      Ain  SpÈcialistes     517
969       02                    Aisne  SpÈcialistes     642
1013      03                   Allier  SpÈcialistes     476
1057      04  Alpes-de-Haute-Provence  SpÈcialistes     193
1101      05             Hautes-Alpes  SpÈcialistes     275

In [203]:
#On étudie uniquement les spécialistes (cheat = specialiste)
df_honoraire = pd.read_excel('/Users/fabienfluro/Documents/MS_BGD/INFMDI721_Kit_DataScience/Repo_Git/Fabien_Fluro/sante/rpps-medecins18-tab2v5_71029108888648.xlsx', sheet_name='honoraire_specialiste', header=[0], skipinitialspace=True, na_values =['nc'])

df_honoraire.head()

,Spécialistes,DEPARTEMENT,EFFECTIFS,HONORAIRES SANS DEPASSEMENT (Euros),DEPASSEMENTS (Euros),FRAIS DE DEPLACEMENT (Euros),TOTAL DES HONORAIRES (Euros)
0,02- Anesthésie-réanimation chirurgicale,01- Ain,17,4530079.33,2496180.45,0.0,7026259.78
1,02- Anesthésie-réanimation chirurgicale,02- Aisne,19,4985259.62,373837.57,0.0,5359097.19
2,02- Anesthésie-réanimation chirurgicale,03- Allier,19,5102901.70,560978.59,0.0,5663880.29
3,02- Anesthésie-réanimation chirurgicale,04- Alpes-Hte-Provence,4,NaN,NaN,NaN,NaN
4,02- Anesthésie-réanimation chirurgicale,05- Hautes-Alpes,5,NaN,NaN,NaN,NaN

In [204]:

# Drop les colonnes inutiles
df_honoraire = df_honoraire.drop(['Spécialistes', 'FRAIS DE DEPLACEMENT (Euros)', 'TOTAL DES HONORAIRES (Euros)'], axis=1)

In [205]:

df_honoraire.head()

df_honoraire.columns = ['DEPARTEMENT', 'EFFECTIFS', 'HONORAIRES_SANS_DEPASSEMENT', 'DEPASSEMENT']

In [206]:

print(len(df_honoraire))

df_honoraire = df_honoraire.dropna()

print(len(df_honoraire))

5512
3213

In [207]:
reg = r'(?P<NUM_DEP>[0-9]{2,3})- (?P<NOM_DEP>.*)'
df_honoraire = pd.concat([df_honoraire, df_honoraire['DEPARTEMENT'].str.extract(reg, expand=True)], axis=1)

In [208]:
df_honoraire = df_honoraire.drop(['DEPARTEMENT'], axis=1)

In [209]:

df_honoraire.head()

,EFFECTIFS,HONORAIRES_SANS_DEPASSEMENT,DEPASSEMENT,NUM_DEP,NOM_DEP
0,17,4530079.33,2496180.45,01,Ain
1,19,4985259.62,373837.57,02,Aisne
2,19,5102901.70,560978.59,03,Allier
5,110,24853773.21,10816346.67,06,Alpes-Maritimes
6,23,5271245.30,802542.01,07,Ardèche

In [210]:
df_honoraire = df_honoraire.groupby('NUM_DEP').sum()

In [212]:
df_honoraire.reset_index()

df_honoraire.head()

         EFFECTIFS  HONORAIRES_SANS_DEPASSEMENT  DEPASSEMENT
NUM_DEP
01            1213                 2.552002e+08  46293197.75
02            1337                 3.094266e+08  17331270.38
03             982                 2.361126e+08  18105662.01
04             410                 7.123895e+07   4725085.98
05             411                 6.522287e+07   2300043.91

In [201]:
df_population = pd.read_excel('/Users/fabienfluro/Documents/MS_BGD/INFMDI721_Kit_DataScience/Repo_Git/Fabien_Fluro/sante/rpps-medecins18-tab2v5_71029108888648.xlsx', sheet_name='population', header=[0], skipinitialspace=True)
df_population.columns = ['NUM_DEP', 'NOM_DEP', 'POPULATION']
df_population.head()

  NUM_DEP                  NOM_DEP  POPULATION
0      01                      Ain      649654
1      02                    Aisne      534286
2      03                   Allier      338978
3      04  Alpes-de-Haute-Provence      161664
4      05             Hautes-Alpes      141576

In [ ]:
df_population = pd.read_excel('/Users/fabienfluro/Documents/MS_BGD/INFMDI721_Kit_DataScience/Repo_Git/Fabien_Fluro/sante/rpps-medecins18-tab2v5_71029108888648.xlsx', sheet_name='population', index_col = [0], header=[0], skipinitialspace=True)

In [98]:
df_medecin.reset_index()

df_medecin = df_medecin.droplevel([0], axis=1)

df_medecin.head(100)

AttributeError: 'DataFrame' object has no attribute 'droplevel'

In [80]:
df_medecin = df_medecin.drop('Moins de 30 ans')
#df_medecin.head()

df_medecin.columns

KeyError: 'Moins de 30 ans'

In [47]:
df_medecin.index.names

FrozenList(['ZONE INSCRIPT', 'SPECIALITE'])

In [56]:
# Afficher toutes les valeurs de l'index 0
# df_medecin.index.get_level_values(0)


df_medecin.xs('Anatomie et cytologie pathologiques', level='SPECIALITE')

,Ensemble tous ages confondus,Moins de 30 ans,Entre 30 et 34 ans,Entre 35 et 39 ans,Entre 40 et 44 ans,Entre 45 et 49 ans,Entre 50 et 54 ans,Entre 55 et 59 ans,Entre 60 et 64 ans,Entre 65 et 69 ans,70 ans et plus
ZONE INSCRIPT,,,,,,,,,,,
FRANCE ENTIERE,1657,19,201,135,137,168,247,260,311,127,52
FRANCE MÈtropolitaine,1632,19,198,131,135,166,244,257,306,126,50
DROM,25,0,3,4,2,2,3,3,5,1,2
Auvergne-RhÙne-Alpes,208,1,34,20,16,22,32,26,39,13,5
Bourgogne-Franche-ComtÈ,48,0,8,4,6,7,5,7,9,2,0
Bretagne,68,0,9,7,5,6,15,9,14,3,0
Centre-Val de Loire,47,0,4,5,3,3,5,9,13,3,2
Corse,6,0,0,0,0,0,1,2,1,2,0
Grand Est,120,3,13,10,10,8,12,19,29,11,5
Guadeloupe,8,0,2,0,0,1,2,1,1,0,1
Guyane,1,0,0,0,0,0,0,0,1,0,0
Hauts-de-France,99,1,14,9,9,9,19,16,17,3,2
Ile-de-France,416,6,47,33,27,40,60,63,80,44,16
La RÈunion,10,0,0,2,2,0,1,1,2,1,1
Martinique,6,0,1,2,0,1,0,1,1,0,0
Mayotte,0,0,0,0,0,0,0,0,0,0,0
Normandie,67,1,8,5,3,8,9,6,13,11,3
Nouvelle-Aquitaine,147,2,18,11,15,21,17,23,28,8,4
Occitanie,168,2,20,5,18,15,30,25,29,17,7
Pays de la Loire,73,2,5,7,8,7,14,19,7,4,0
Provence-Alpes-CÙte díAzur,165,1,18,15,15,20,25,33,27,5,6
01 - Ain,3,0,0,0,1,0,0,0,2,0,0
02 - Aisne,5,0,0,1,1,1,0,1,0,0,1
03 - Allier,2,0,0,0,0,0,0,0,1,0,1
04 - Alpes-de-Haute-Provence,3,0,0,0,0,0,1,1,0,0,1
05 - Hautes-Alpes,2,0,1,0,0,1,0,0,0,0,0
06 - Alpes-Maritimes,50,1,7,5,2,5,8,11,7,1,3
07 - ArdËche,0,0,0,0,0,0,0,0,0,0,0
08 - Ardennes,2,0,0,0,1,0,0,1,0,0,0
09 - AriËge,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
71 - SaÙne-et-Loire,4,0,0,1,0,1,1,0,1,0,0
72 - Sarthe,10,0,1,1,1,0,2,4,0,1,0
73 - Savoie,11,0,2,0,1,0,3,2,3,0,0
74 - Haute-Savoie,10,0,0,2,0,1,1,2,2,2,0
75 - Paris,216,4,25,18,12,17,31,29,43,27,10
76 - Seine-Maritime,35,1,6,3,1,3,3,5,4,9,0
77 - Seine-et-Marne,13,0,1,0,2,0,5,3,2,0,0
78 - Yvelines,23,1,1,1,1,3,3,5,7,0,1
79 - Deux-SËvres,4,0,0,0,0,2,1,0,1,0,0
80 - Somme,14,0,1,0,2,0,5,2,4,0,0
81 - Tarn,2,0,0,0,0,0,0,0,2,0,0
82 - Tarn-et-Garonne,7,0,0,0,0,1,1,3,1,1,0
83 - Var,25,0,3,1,4,4,2,4,6,0,1
84 - Vaucluse,15,0,0,2,1,0,5,4,3,0,0
85 - VendÈe,5,0,1,0,1,0,0,2,1,0,0
86 - Vienne,13,0,3,0,1,2,0,4,3,0,0
87 - Haute-Vienne,17,1,2,0,1,4,1,3,3,1,1
88 - Vosges,4,0,0,0,2,0,0,0,1,1,0
89 - Yonne,2,0,0,1,0,0,0,0,1,0,0
90 - Territoire de Belfort,6,0,2,0,0,0,1,2,1,0,0
91 - Essonne,16,0,1,0,1,3,4,2,5,0,0
92 - Hauts-de-Seine,54,0,7,4,6,4,4,11,11,6,1
93 - Seine-Saint-Denis,17,0,0,1,1,3,4,5,1,1,1
94 - Val-de-Marne,56,0,11,8,3,6,6,8,5,7,2
95 - Val-díOise,21,1,1,1,1,4,3,0,6,3,1
971 - Guadeloupe,8,0,2,0,0,1,2,1,1,0,1
972 - Martinique,6,0,1,2,0,1,0,1,1,0,0
973 - Guyane,1,0,0,0,0,0,0,0,1,0,0
974 - La RÈunion,10,0,0,2,2,0,1,1,2,1,1
976 - Mayotte,0,0,0,0,0,0,0,0,0,0,0

In [77]:
df_honoraire = pd.read_excel('/Users/fabienfluro/Documents/MS_BGD/INFMDI721_Kit_DataScience/Repo_Git/Fabien_Fluro/sante/Honoraires_totaux_des_professionnels_de_sante_par_departement_en_2016.xls', sheet_name='Spécialistes', header=[0], skipinitialspace=True, na_values=['nc'])
df_honoraire.head()

print(len(df_honoraire))

df_honoraire.dropna()

print(len(df_honoraire))

5512
5512

In [ ]:
df_region = pd.read_excel('/Users/fabienfluro/Documents/MS_BGD/INFMDI721_Kit_DataScience/Repo_Git/Fabien_Fluro/sante/rpps-medecins18-tab2v5_71029108888648.xlsx', sheet_name='population', header=[0, 1], skipinitialspace=True)
df_region.reset_index()
df_region.head(100)

In [67]:
df_region.index.names

FrozenList([None, None])

In [61]:
df_region['Départements',0]

KeyError: ('Départements', 0)